### ISSUE TITLE
Scaffold renames translator files when saving

### ISSUE THREAD

**Issue by aurimasv** [zotero/scaffold#13] opened 2012-09-19 05:31 UTC
If the translator name in the JSON header does not match the actual file name, Scaffold renames the file and breaks Git tracking.

Scaffold should not change translator file names (though we should also be consistent with translator names and file names, but what's done is done).

Slightly related to zotero/translators#459

**Comment by zuphilip** [comment] 2018-05-05 11:53
Git can also find renamed files when they did not completely changed their content as well. Actually, most of the file names as well as the labels are now renamed to an ASCII variant. Thus, I don't think this is much a problem anymore, maybe we can call this renaming within Scaffold nowadays even a feature (and not a bug anymore).

Closing this issue now.

**Closed by zuphilip** 2018-05-05 11:53 UTC
